version: "3.9"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=369963

    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "sleep 15 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/

    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=369963
    depends_on:
      - db
